/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladora.ControladoraFacturas;
import Modelo.Factura;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hatake
 */
public class jdFacturaDetallada extends javax.swing.JDialog {

    /**
     * Creates new form jdFacturaDetallada
     */
    
    private ControladoraFacturas facturas= new ControladoraFacturas();
    private Factura f;
    private int x,y;
    
    
    public void cargarDatos()
    {        
        try
        {                
            String col[] = {"Nro Item","Cantidad","Producto","Precio","Importe"};                                                 
            
            DefaultTableModel tableModel = new DefaultTableModel(col,0){
                @Override
                public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
            };
            
            jtFacturas.setModel(tableModel);

            f.getDetalleFactura().forEach((df) -> 
            {                                   
                //"Nro Item","Cantidad","Producto","Precio"
                Object[] datos = {String.valueOf(df.getNroItem()), String.valueOf(df.getCantidad()),
                    df.getProducto().getNombre(),"$ "+ String.format( "%.2f",df.getProducto().getPrecio()), "$ "+ String.format( "%.2f",df.getCantidad()* df.getProducto().getPrecio()) };            
                tableModel.addRow(datos);                   
            });                          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Se ha producido un error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    public jdFacturaDetallada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public jdFacturaDetallada(javax.swing.JDialog parent, boolean modal,int id) {
        super(parent, modal);
        initComponents();
        
        try
        {
            f=facturas.BuscarFacturaPorNro(id);
            if(f!=null)
            {
                cargarDatos();
                jtxtNroFactura.setText(String.valueOf(f.getNroFactura()));
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");	
                Date fecha= f.getFecha();
                
                jtxtFecha.setText(dateFormat.format(fecha));
                jtxtCliente.setText(f.getCliente().getApellido()+", "+ f.getCliente().getNombre());
                
                jtxtTotalSinIva.setText("$ "+String.format( "%.2f",f.getTotalSinIva()));
                
                jlblIva.setText("IVA("+ String.valueOf(f.getIva()) +"%)");
                double ivaCalculado=f.getTotalConIva()-f.getTotalSinIva();
                jtxtIva.setText("$"+String.format( "%.2f",ivaCalculado));
                
                jtxtTotalConIva.setText("$ "+String.format( "%.2f",f.getTotalConIva()));
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Se ha producido un error", JOptionPane.ERROR_MESSAGE);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpClientes = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jbtnCerrar = new javax.swing.JButton();
        jpSeparador = new javax.swing.JPanel();
        jpPrincipal = new javax.swing.JPanel();
        jpFactura = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFacturas = new javax.swing.JTable();
        jlblNroFactura = new javax.swing.JLabel();
        jtxtNroFactura = new javax.swing.JTextField();
        jlblFecha = new javax.swing.JLabel();
        jtxtFecha = new javax.swing.JTextField();
        jlblCliente = new javax.swing.JLabel();
        jtxtCliente = new javax.swing.JTextField();
        jlblTotalSinIva = new javax.swing.JLabel();
        jtxtTotalSinIva = new javax.swing.JTextField();
        jlblIva = new javax.swing.JLabel();
        jtxtIva = new javax.swing.JTextField();
        jlblTotalIva = new javax.swing.JLabel();
        jtxtTotalConIva = new javax.swing.JTextField();
        jlblFactura = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpClientes.setBackground(new java.awt.Color(0, 0, 0));
        jpClientes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpClientesMouseDragged(evt);
            }
        });
        jpClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpClientesMousePressed(evt);
            }
        });
        jpClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlblTitulo.setText("Detalles Factura");
        jlblTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlblTituloMouseDragged(evt);
            }
        });
        jlblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlblTituloMousePressed(evt);
            }
        });
        jpClientes.add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 170, -1));

        jbtnCerrar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jbtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCerrar.setText("x");
        jbtnCerrar.setBorder(null);
        jbtnCerrar.setBorderPainted(false);
        jbtnCerrar.setContentAreaFilled(false);
        jbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarActionPerformed(evt);
            }
        });
        jpClientes.add(jbtnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 40));

        getContentPane().add(jpClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        jpSeparador.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jpSeparadorLayout = new javax.swing.GroupLayout(jpSeparador);
        jpSeparador.setLayout(jpSeparadorLayout);
        jpSeparadorLayout.setHorizontalGroup(
            jpSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jpSeparadorLayout.setVerticalGroup(
            jpSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jpSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 780, 10));

        jpPrincipal.setBackground(java.awt.SystemColor.controlHighlight);
        jpPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        jpFactura.setBackground(java.awt.SystemColor.controlShadow);

        jtFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtFacturas.setRowHeight(24);
        jScrollPane1.setViewportView(jtFacturas);

        javax.swing.GroupLayout jpFacturaLayout = new javax.swing.GroupLayout(jpFactura);
        jpFactura.setLayout(jpFacturaLayout);
        jpFacturaLayout.setHorizontalGroup(
            jpFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFacturaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFacturaLayout.setVerticalGroup(
            jpFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFacturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jlblNroFactura.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblNroFactura.setText("Nro Factura:");

        jtxtNroFactura.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtxtNroFactura.setEnabled(false);

        jlblFecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblFecha.setText("Fecha:");

        jtxtFecha.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtxtFecha.setEnabled(false);

        jlblCliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblCliente.setText("Cliente:");

        jtxtCliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtxtCliente.setEnabled(false);

        jlblTotalSinIva.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblTotalSinIva.setText("Total:");

        jtxtTotalSinIva.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtxtTotalSinIva.setEnabled(false);

        jlblIva.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblIva.setText("IVA(%)");

        jtxtIva.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtxtIva.setEnabled(false);

        jlblTotalIva.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblTotalIva.setText("Total c/IVA");

        jtxtTotalConIva.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtxtTotalConIva.setEnabled(false);

        jlblFactura.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblFactura.setText("Factura:");

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(jlblFactura)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jlblNroFactura)
                        .addGap(4, 4, 4)
                        .addComponent(jtxtNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jlblFecha)
                        .addGap(7, 7, 7)
                        .addComponent(jtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addComponent(jlblCliente)
                        .addGap(11, 11, 11)
                        .addComponent(jtxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jlblTotalIva)
                                .addGap(7, 7, 7)
                                .addComponent(jtxtTotalConIva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jlblIva)
                                .addGap(7, 7, 7)
                                .addComponent(jtxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPrincipalLayout.createSequentialGroup()
                                .addComponent(jlblTotalSinIva)
                                .addGap(7, 7, 7)
                                .addComponent(jtxtTotalSinIva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblNroFactura)
                    .addComponent(jtxtNroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblFecha)
                    .addComponent(jtxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCliente)
                    .addComponent(jtxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotalSinIva)
                    .addComponent(jtxtTotalSinIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblIva)
                    .addComponent(jtxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotalIva)
                    .addComponent(jtxtTotalConIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 780, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnCerrarActionPerformed

    private void jlblTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblTituloMousePressed
        // TODO add your handling code here:
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_jlblTituloMousePressed

    private void jpClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpClientesMousePressed
        // TODO add your handling code here:
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_jpClientesMousePressed

    private void jlblTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblTituloMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y+ evt.getY()- y);                        
    }//GEN-LAST:event_jlblTituloMouseDragged

    private void jpClientesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpClientesMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y+ evt.getY()- y);                        
    }//GEN-LAST:event_jpClientesMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdFacturaDetallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdFacturaDetallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdFacturaDetallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdFacturaDetallada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdFacturaDetallada dialog = new jdFacturaDetallada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JLabel jlblCliente;
    private javax.swing.JLabel jlblFactura;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblIva;
    private javax.swing.JLabel jlblNroFactura;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTotalIva;
    private javax.swing.JLabel jlblTotalSinIva;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpFactura;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpSeparador;
    private javax.swing.JTable jtFacturas;
    private javax.swing.JTextField jtxtCliente;
    private javax.swing.JTextField jtxtFecha;
    private javax.swing.JTextField jtxtIva;
    private javax.swing.JTextField jtxtNroFactura;
    private javax.swing.JTextField jtxtTotalConIva;
    private javax.swing.JTextField jtxtTotalSinIva;
    // End of variables declaration//GEN-END:variables
}
