/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controladora.ControladoraClientes;
import Controladora.ControladoraFacturas;
import Controladora.ControladoraProductos;
import Modelo.MiSesion;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Hatake
 */
public class jfPrincipal extends javax.swing.JFrame {

    private int x,y;
    private MiSesion s= new MiSesion();
    
    private ControladoraClientes clientes= new ControladoraClientes();
    private ControladoraProductos productos= new ControladoraProductos();
    private ControladoraFacturas facturas= new ControladoraFacturas();
    
    public void obtenerDatos()
    {
        try
        {
            this.jlblCantidadClientes.setText(""+clientes.DevolverClientes().size());
            this.jlblCantidadProductos.setText(""+productos.DevolverProductos().size());
            this.jlblCantidadFacturas.setText(""+ facturas.DevolverFacturas().size());
            this.jlblCantidadVentas.setText(""+ facturas.CantidadProductosVendidos());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Se ha producido un error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Creates new form jfPrincipal
     */
    public jfPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        MiSesion.AbrirSesion();
        
        
        obtenerDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitulo = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jbtnSalir = new javax.swing.JButton();
        jpSeparador = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jpTelefonos = new javax.swing.JPanel();
        jpTelefonosLateral = new javax.swing.JPanel();
        jbtnOtros = new javax.swing.JButton();
        jpClientes = new javax.swing.JPanel();
        jpClientesLateral = new javax.swing.JPanel();
        jbtnClientes = new javax.swing.JButton();
        jpProductos = new javax.swing.JPanel();
        jpProductosLateral = new javax.swing.JPanel();
        jbtnProductos = new javax.swing.JButton();
        jpVentas = new javax.swing.JPanel();
        jpVentasLateral = new javax.swing.JPanel();
        jbtnVentas = new javax.swing.JButton();
        jpFacturas = new javax.swing.JPanel();
        jpFacturasLateral = new javax.swing.JPanel();
        jbtnFacturas = new javax.swing.JButton();
        jpPrincipal = new javax.swing.JPanel();
        jlblInformacion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jpDatos = new javax.swing.JPanel();
        jpProductosInformacion = new javax.swing.JPanel();
        jlblCantidadProductos = new javax.swing.JLabel();
        jlblProductos = new javax.swing.JLabel();
        jbIconoProductos = new javax.swing.JButton();
        jpClientesInformacion = new javax.swing.JPanel();
        jlblCantidadClientes = new javax.swing.JLabel();
        jlblClientes = new javax.swing.JLabel();
        jbIconoClientes = new javax.swing.JButton();
        jpVentasInformacion = new javax.swing.JPanel();
        jlblCantidadVentas = new javax.swing.JLabel();
        jlblVentas = new javax.swing.JLabel();
        jbIconoVentas = new javax.swing.JButton();
        jlblVentas1 = new javax.swing.JLabel();
        jpFacturasInformacion = new javax.swing.JPanel();
        jlblCantidadFacturas = new javax.swing.JLabel();
        jlblFacturas = new javax.swing.JLabel();
        jbIconoFacturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(748, 40));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jpTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpTituloMouseDragged(evt);
            }
        });
        jpTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpTituloMousePressed(evt);
            }
        });
        jpTitulo.setLayout(null);

        jlblTitulo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlblTitulo.setText("Bienvenido");
        jlblTitulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jlblTituloMouseDragged(evt);
            }
        });
        jlblTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlblTituloMousePressed(evt);
            }
        });
        jpTitulo.add(jlblTitulo);
        jlblTitulo.setBounds(300, 10, 126, 24);

        jbtnSalir.setBackground(new java.awt.Color(0, 0, 0));
        jbtnSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jbtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shutdown_26.png"))); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.setBorder(null);
        jbtnSalir.setBorderPainted(false);
        jbtnSalir.setContentAreaFilled(false);
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        jpTitulo.add(jbtnSalir);
        jbtnSalir.setBounds(630, 0, 110, 40);

        getContentPane().add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 40));

        jpSeparador.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jpSeparadorLayout = new javax.swing.GroupLayout(jpSeparador);
        jpSeparador.setLayout(jpSeparadorLayout);
        jpSeparadorLayout.setHorizontalGroup(
            jpSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jpSeparadorLayout.setVerticalGroup(
            jpSeparadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jpSeparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jpMenu.setBackground(new java.awt.Color(51, 51, 51));
        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTelefonos.setBackground(new java.awt.Color(0, 0, 0));
        jpTelefonos.setLayout(null);

        jpTelefonosLateral.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout jpTelefonosLateralLayout = new javax.swing.GroupLayout(jpTelefonosLateral);
        jpTelefonosLateral.setLayout(jpTelefonosLateralLayout);
        jpTelefonosLateralLayout.setHorizontalGroup(
            jpTelefonosLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jpTelefonosLateralLayout.setVerticalGroup(
            jpTelefonosLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpTelefonos.add(jpTelefonosLateral);
        jpTelefonosLateral.setBounds(0, 0, 8, 40);

        jbtnOtros.setBackground(new java.awt.Color(0, 0, 0));
        jbtnOtros.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtnOtros.setForeground(new java.awt.Color(255, 255, 255));
        jbtnOtros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuration_20.png"))); // NOI18N
        jbtnOtros.setText("Otros");
        jbtnOtros.setBorder(null);
        jbtnOtros.setBorderPainted(false);
        jbtnOtros.setContentAreaFilled(false);
        jbtnOtros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOtrosActionPerformed(evt);
            }
        });
        jpTelefonos.add(jbtnOtros);
        jbtnOtros.setBounds(20, 0, 120, 40);

        jpMenu.add(jpTelefonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 40));

        jpClientes.setBackground(new java.awt.Color(0, 0, 0));
        jpClientes.setLayout(null);

        jpClientesLateral.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jpClientesLateralLayout = new javax.swing.GroupLayout(jpClientesLateral);
        jpClientesLateral.setLayout(jpClientesLateralLayout);
        jpClientesLateralLayout.setHorizontalGroup(
            jpClientesLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jpClientesLateralLayout.setVerticalGroup(
            jpClientesLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpClientes.add(jpClientesLateral);
        jpClientesLateral.setBounds(0, 0, 8, 40);

        jbtnClientes.setBackground(new java.awt.Color(0, 0, 0));
        jbtnClientes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtnClientes.setForeground(new java.awt.Color(255, 255, 255));
        jbtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Customer_26.png"))); // NOI18N
        jbtnClientes.setText("Clientes");
        jbtnClientes.setBorder(null);
        jbtnClientes.setBorderPainted(false);
        jbtnClientes.setContentAreaFilled(false);
        jbtnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClientesActionPerformed(evt);
            }
        });
        jpClientes.add(jbtnClientes);
        jbtnClientes.setBounds(20, 0, 120, 40);

        jpMenu.add(jpClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 40));

        jpProductos.setBackground(new java.awt.Color(0, 0, 0));
        jpProductos.setLayout(null);

        jpProductosLateral.setBackground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout jpProductosLateralLayout = new javax.swing.GroupLayout(jpProductosLateral);
        jpProductosLateral.setLayout(jpProductosLateralLayout);
        jpProductosLateralLayout.setHorizontalGroup(
            jpProductosLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jpProductosLateralLayout.setVerticalGroup(
            jpProductosLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpProductos.add(jpProductosLateral);
        jpProductosLateral.setBounds(0, 0, 8, 40);

        jbtnProductos.setBackground(new java.awt.Color(0, 0, 0));
        jbtnProductos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtnProductos.setForeground(new java.awt.Color(255, 255, 255));
        jbtnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Barcode_26.png"))); // NOI18N
        jbtnProductos.setText("Productos");
        jbtnProductos.setBorder(null);
        jbtnProductos.setBorderPainted(false);
        jbtnProductos.setContentAreaFilled(false);
        jbtnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProductosActionPerformed(evt);
            }
        });
        jpProductos.add(jbtnProductos);
        jbtnProductos.setBounds(20, 0, 120, 40);

        jpMenu.add(jpProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, 40));

        jpVentas.setBackground(new java.awt.Color(0, 0, 0));
        jpVentas.setLayout(null);

        jpVentasLateral.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jpVentasLateralLayout = new javax.swing.GroupLayout(jpVentasLateral);
        jpVentasLateral.setLayout(jpVentasLateralLayout);
        jpVentasLateralLayout.setHorizontalGroup(
            jpVentasLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jpVentasLateralLayout.setVerticalGroup(
            jpVentasLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpVentas.add(jpVentasLateral);
        jpVentasLateral.setBounds(0, 0, 8, 40);

        jbtnVentas.setBackground(new java.awt.Color(0, 0, 0));
        jbtnVentas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtnVentas.setForeground(new java.awt.Color(255, 255, 255));
        jbtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shopping_Cart_26.png"))); // NOI18N
        jbtnVentas.setText("Ventas");
        jbtnVentas.setBorder(null);
        jbtnVentas.setBorderPainted(false);
        jbtnVentas.setContentAreaFilled(false);
        jbtnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVentasActionPerformed(evt);
            }
        });
        jpVentas.add(jbtnVentas);
        jbtnVentas.setBounds(20, 0, 120, 40);

        jpMenu.add(jpVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 40));

        jpFacturas.setBackground(new java.awt.Color(0, 0, 0));
        jpFacturas.setLayout(null);

        jpFacturasLateral.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jpFacturasLateralLayout = new javax.swing.GroupLayout(jpFacturasLateral);
        jpFacturasLateral.setLayout(jpFacturasLateralLayout);
        jpFacturasLateralLayout.setHorizontalGroup(
            jpFacturasLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jpFacturasLateralLayout.setVerticalGroup(
            jpFacturasLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jpFacturas.add(jpFacturasLateral);
        jpFacturasLateral.setBounds(0, 0, 8, 40);

        jbtnFacturas.setBackground(new java.awt.Color(0, 0, 0));
        jbtnFacturas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jbtnFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jbtnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Purchase_Order_26.png"))); // NOI18N
        jbtnFacturas.setText("Facturas");
        jbtnFacturas.setBorder(null);
        jbtnFacturas.setBorderPainted(false);
        jbtnFacturas.setContentAreaFilled(false);
        jbtnFacturas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFacturasActionPerformed(evt);
            }
        });
        jpFacturas.add(jbtnFacturas);
        jbtnFacturas.setBounds(20, 0, 120, 40);

        jpMenu.add(jpFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 40));

        getContentPane().add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 360));

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jpPrincipal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        jlblInformacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblInformacion.setForeground(new java.awt.Color(153, 153, 153));
        jlblInformacion.setText("Información");

        jpProductosInformacion.setBackground(new java.awt.Color(255, 0, 102));
        jpProductosInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCantidadProductos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblCantidadProductos.setForeground(new java.awt.Color(255, 255, 255));
        jlblCantidadProductos.setText("0");
        jpProductosInformacion.add(jlblCantidadProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 73, 26));

        jlblProductos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblProductos.setForeground(new java.awt.Color(255, 255, 255));
        jlblProductos.setText("Productos");
        jpProductosInformacion.add(jlblProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 26));

        jbIconoProductos.setBackground(new java.awt.Color(51, 102, 255));
        jbIconoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Barcode_100.png"))); // NOI18N
        jbIconoProductos.setBorder(null);
        jbIconoProductos.setBorderPainted(false);
        jbIconoProductos.setContentAreaFilled(false);
        jpProductosInformacion.add(jbIconoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 90));

        jpClientesInformacion.setBackground(new java.awt.Color(51, 102, 255));
        jpClientesInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCantidadClientes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblCantidadClientes.setForeground(new java.awt.Color(255, 255, 255));
        jlblCantidadClientes.setText("0");
        jpClientesInformacion.add(jlblCantidadClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 73, 26));

        jlblClientes.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblClientes.setForeground(new java.awt.Color(255, 255, 255));
        jlblClientes.setText("Clientes");
        jpClientesInformacion.add(jlblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 73, 26));

        jbIconoClientes.setBackground(new java.awt.Color(51, 102, 255));
        jbIconoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Customer_100.png"))); // NOI18N
        jbIconoClientes.setBorder(null);
        jbIconoClientes.setBorderPainted(false);
        jbIconoClientes.setContentAreaFilled(false);
        jpClientesInformacion.add(jbIconoClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 90));

        jpVentasInformacion.setBackground(new java.awt.Color(255, 204, 51));
        jpVentasInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCantidadVentas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblCantidadVentas.setForeground(new java.awt.Color(255, 255, 255));
        jlblCantidadVentas.setText("0");
        jpVentasInformacion.add(jlblCantidadVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 73, 26));

        jlblVentas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblVentas.setForeground(new java.awt.Color(255, 255, 255));
        jlblVentas.setText("Vendidos");
        jpVentasInformacion.add(jlblVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, 30));

        jbIconoVentas.setBackground(new java.awt.Color(51, 102, 255));
        jbIconoVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shopping_Cart_100.png"))); // NOI18N
        jbIconoVentas.setBorder(null);
        jbIconoVentas.setBorderPainted(false);
        jbIconoVentas.setContentAreaFilled(false);
        jpVentasInformacion.add(jbIconoVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 90));

        jlblVentas1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblVentas1.setForeground(new java.awt.Color(255, 255, 255));
        jlblVentas1.setText("Productos");
        jpVentasInformacion.add(jlblVentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, 30));

        jpFacturasInformacion.setBackground(new java.awt.Color(153, 204, 255));
        jpFacturasInformacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCantidadFacturas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblCantidadFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jlblCantidadFacturas.setText("0");
        jpFacturasInformacion.add(jlblCantidadFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 73, 26));

        jlblFacturas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblFacturas.setForeground(new java.awt.Color(255, 255, 255));
        jlblFacturas.setText("Facturas");
        jpFacturasInformacion.add(jlblFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 26));

        jbIconoFacturas.setBackground(new java.awt.Color(51, 102, 255));
        jbIconoFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Purchase_Order_100.png"))); // NOI18N
        jbIconoFacturas.setBorder(null);
        jbIconoFacturas.setBorderPainted(false);
        jbIconoFacturas.setContentAreaFilled(false);
        jpFacturasInformacion.add(jbIconoFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 90));

        javax.swing.GroupLayout jpDatosLayout = new javax.swing.GroupLayout(jpDatos);
        jpDatos.setLayout(jpDatosLayout);
        jpDatosLayout.setHorizontalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpClientesInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpVentasInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpProductosInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpFacturasInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jpDatosLayout.setVerticalGroup(
            jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpClientesInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpProductosInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpVentasInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpFacturasInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpPrincipalLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 580, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOtrosActionPerformed
        try {
            // TODO add your handling code here:
            facturas.ModificarDetallesFactura();
            JOptionPane.showMessageDialog(null,"Se han modificado los detalles de factura con éxito.",  "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Se ha producido un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnOtrosActionPerformed

    private void jbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClientesActionPerformed
        // TODO add your handling code here:
        try
        {            
            jdClientesMostrar clientes= new jdClientesMostrar(this,true);
            clientes.setLocationRelativeTo (null);
            clientes.setVisible(true);            
                        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Se ha producido un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnClientesActionPerformed

    private void jbtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProductosActionPerformed
        // TODO add your handling code here:
            jdProductosMostrar productos= new jdProductosMostrar(this,true);
            productos.setLocationRelativeTo (null);
            productos.setVisible(true);
    }//GEN-LAST:event_jbtnProductosActionPerformed

    private void jbtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVentasActionPerformed
        // TODO add your handling code here:
        jdFacturasAgregar facturas= new jdFacturasAgregar(this,true);
        facturas.setLocationRelativeTo(null);
        facturas.setVisible(true);
    }//GEN-LAST:event_jbtnVentasActionPerformed

    private void jbtnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFacturasActionPerformed
        // TODO add your handling code here:
        try
        {            
            jdFacturasMostrar facturas= new jdFacturasMostrar(this,true);
            facturas.setLocationRelativeTo (null);
            facturas.setVisible(true);
                        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Mensaje:"+ e.getMessage() + "Causa:"+e.getCause(), "Se ha producido un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnFacturasActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        try
        {
            MiSesion.CerrarSesion();                        
            System.exit(0);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Mensaje:"+ e.getMessage() + "Causa:"+e.getCause(), "Se ha producido un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jpTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTituloMousePressed
        // TODO add your handling code here:
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_jpTituloMousePressed

    private void jlblTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblTituloMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y+ evt.getY()- y);                        
    }//GEN-LAST:event_jlblTituloMouseDragged

    private void jpTituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpTituloMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX()-x, this.getLocation().y+ evt.getY()- y);                        
    }//GEN-LAST:event_jpTituloMouseDragged

    private void jlblTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblTituloMousePressed
        // TODO add your handling code here:
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_jlblTituloMousePressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        obtenerDatos();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbIconoClientes;
    private javax.swing.JButton jbIconoFacturas;
    private javax.swing.JButton jbIconoProductos;
    private javax.swing.JButton jbIconoVentas;
    private javax.swing.JButton jbtnClientes;
    private javax.swing.JButton jbtnFacturas;
    private javax.swing.JButton jbtnOtros;
    private javax.swing.JButton jbtnProductos;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnVentas;
    private javax.swing.JLabel jlblCantidadClientes;
    private javax.swing.JLabel jlblCantidadFacturas;
    private javax.swing.JLabel jlblCantidadProductos;
    private javax.swing.JLabel jlblCantidadVentas;
    private javax.swing.JLabel jlblClientes;
    private javax.swing.JLabel jlblFacturas;
    private javax.swing.JLabel jlblInformacion;
    private javax.swing.JLabel jlblProductos;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblVentas;
    private javax.swing.JLabel jlblVentas1;
    private javax.swing.JPanel jpClientes;
    private javax.swing.JPanel jpClientesInformacion;
    private javax.swing.JPanel jpClientesLateral;
    private javax.swing.JPanel jpDatos;
    private javax.swing.JPanel jpFacturas;
    private javax.swing.JPanel jpFacturasInformacion;
    private javax.swing.JPanel jpFacturasLateral;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JPanel jpProductos;
    private javax.swing.JPanel jpProductosInformacion;
    private javax.swing.JPanel jpProductosLateral;
    private javax.swing.JPanel jpSeparador;
    private javax.swing.JPanel jpTelefonos;
    private javax.swing.JPanel jpTelefonosLateral;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel jpVentas;
    private javax.swing.JPanel jpVentasInformacion;
    private javax.swing.JPanel jpVentasLateral;
    // End of variables declaration//GEN-END:variables
}
